#!/usr/sbin/expect


set username "admin"
set password "admin"
set sw [lindex $argv 0]


spawn telnet $sw
expect "*Username*" {send "$username\r"}
sleep 2
expect "*Password*" {send "$password\r"}
sleep 2
send "enable\r"
sleep 2
expect "*Password*" {send "$password\r"}
sleep 2
send "conf t\r"
sleep 2
send "ip domain-name name.dom\r"
sleep 2
send "crypto key generate rsa general-keys modulus 2048\r"
sleep 2
send "ip ssh version 2\r"
sleep 2
send "exit\n"
interact timeout 2 return
